const characters = [
    // tekken 1
    { "id": "anna", "name": "Anna Williams", "nationality": "Ireland", "style": "Aikido", "games": ["tekken1",] },
    { "id": "jack", "name": "Jack", "nationality": "Russia", "style": "Brute force", "games": ["tekken1",]},
    { "id": "kazuya", "name": "Kazuya Mishima", "nationality": "Japan", "style": "Mishima Style Fighting Karate", "games": ["tekken1",] },
    { "id": "kingi", "name": "King I", "nationality": "Mexico", "dead": true, "style": "Pro-Wrestling", "games": ["tekken1",] },
    { "id": "law", "name": "Marshall Law", "nationality": "United States of America", "style": "Martial Arts", "games": ["tekken1",]},
    { "id": "michelle", "name": "Michelle Chang", "nationality": "United States of America", "style": "All types of Chinese fighting arts", "games": ["tekken1",] },
    { "id": "nina", "name": "Nina Williams", "nationality": "Ireland", "style": "Aikido", "games": ["tekken1",] },
    { "id": "paul", "name": "Paul Phoenix", "nationality": "United States of America", "style": "Integrated Martial Arts", "games": ["tekken1",] },
    { "id": "yoshimitsu", "name": "Yoshimitsu", "nationality": "Japan", "style": "Advanced Manji Ninjutsu", "games": ["tekken1",] },
    { "id": "akingi", "name": "Armor King I", "nationality": "Unknown", "dead": true, "style": "Pro-Wrestling", "games": ["tekken1",] },
    { "id": "devil", "name": "Devil Kazuya", "nationality": "Unknown", "style": "Unknown", "games": ["tekken1",] },
    { "id": "ganryu", "name": "Ganryu", "nationality": "Japan", "style": "Sumo", "games": ["tekken1",] },
    { "id": "heihachi", "name": "Heihachi Mishima", "nationality": "Japan", "style": "Mishima Style Fighting Karate", "games": ["tekken1",] },
    { "id": "kumai", "name": "Kuma I", "nationality": "Japan", "style": "Heihachi-style Kuma Shinken", "games": ["tekken1",] },
    { "id": "kunii", "name": "Kunimitsu I", "nationality": "Japan", "style": "Manji Ninjutsu", "games": ["tekken1",] },
    { "id": "lee", "name": "Lee Chaolan", "nationality": "Japan", "style": "Mishima Style Fighting Karate", "games": ["tekken1",] },
    { "id": "pjack", "name": "Prototype Jack", "nationality": "Russia", "style": "Brute Force", "games": ["tekken1",] },
    { "id": "wang", "name": "Wang Jinrei", "nationality": "China", "style": "Xin Yi Liu He Quan", "games": ["tekken1",] },
];